// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AxiomPrimeServer.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260805191006_AddMissionPayload")]
    partial class AddMissionPayload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Currencies", b =>
                {
                    b.Property<string>("PlayerID")
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<int>("PremiumCredits")
                        .HasColumnType("integer");

                    b.Property<int>("Scrap")
                        .HasColumnType("integer");

                    b.HasKey("PlayerID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Energy", b =>
                {
                    b.Property<string>("PlayerID")
                        .HasColumnType("text");

                    b.Property<float>("CurrentEnergy")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MaxEnergy")
                        .HasColumnType("real");

                    b.Property<float>("RegenSpeed")
                        .HasColumnType("real");

                    b.HasKey("PlayerID");

                    b.ToTable("Energies");
                });

            modelBuilder.Entity("Experience", b =>
                {
                    b.Property<string>("PlayerID")
                        .HasColumnType("text");

                    b.Property<int>("CurrentExperience")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("NextLevelExperience")
                        .HasColumnType("integer");

                    b.HasKey("PlayerID");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Inventory", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int>("numOfItems")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Item_Database", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("InventoryPlayerId")
                        .HasColumnType("text");

                    b.Property<string>("ItemDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ItemData");

                    b.Property<float>("Power")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPlayerId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Mission_Database", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("MissionDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("MissionData");

                    b.HasKey("PlayerId");

                    b.ToTable("Missions", (string)null);
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ShipInventory", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int>("NumOfShips")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("ShipInventories");
                });

            modelBuilder.Entity("ShipItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipItem");
                });

            modelBuilder.Entity("Ship_Database", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxExp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ShipDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ShipData");

                    b.Property<string>("ShipInventoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("XOrigin")
                        .HasColumnType("integer");

                    b.Property<int>("YOrigin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShipInventoryId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("Currencies", b =>
                {
                    b.HasOne("Player", null)
                        .WithOne("Currencies")
                        .HasForeignKey("Currencies", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Energy", b =>
                {
                    b.HasOne("Player", null)
                        .WithOne("Energy")
                        .HasForeignKey("Energy", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Experience", b =>
                {
                    b.HasOne("Player", null)
                        .WithOne("Experience")
                        .HasForeignKey("Experience", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Item_Database", b =>
                {
                    b.HasOne("Inventory", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryPlayerId");
                });

            modelBuilder.Entity("ShipItem", b =>
                {
                    b.HasOne("Item_Database", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ship_Database", "Ship")
                        .WithMany("Items")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Ship_Database", b =>
                {
                    b.HasOne("ShipInventory", "ShipInventory")
                        .WithMany("Ships")
                        .HasForeignKey("ShipInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipInventory");
                });

            modelBuilder.Entity("Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Navigation("Currencies");

                    b.Navigation("Energy");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("ShipInventory", b =>
                {
                    b.Navigation("Ships");
                });

            modelBuilder.Entity("Ship_Database", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
