// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AxiomPrimeServer.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Currencies", b =>
                {
                    b.Property<string>("PlayerID")
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<int>("PremiumCredits")
                        .HasColumnType("integer");

                    b.Property<int>("Scrap")
                        .HasColumnType("integer");

                    b.HasKey("PlayerID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Energy", b =>
                {
                    b.Property<string>("PlayerID")
                        .HasColumnType("text");

                    b.Property<float>("CurrentEnergy")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("MaxEnergy")
                        .HasColumnType("real");

                    b.Property<float>("RegenSpeed")
                        .HasColumnType("real");

                    b.HasKey("PlayerID");

                    b.ToTable("Energies");
                });

            modelBuilder.Entity("Experience", b =>
                {
                    b.Property<string>("PlayerID")
                        .HasColumnType("text");

                    b.Property<int>("CurrentExperience")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("NextLevelExperience")
                        .HasColumnType("integer");

                    b.HasKey("PlayerID");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Inventory", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int>("numOfItems")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("InventoryPlayerId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<float>("Power")
                        .HasColumnType("real");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryPlayerId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("ShipInventoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XOrigin")
                        .HasColumnType("integer");

                    b.Property<int>("YOrigin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShipInventoryId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("ShipInventory", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int>("NumOfShips")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("ShipInventories");
                });

            modelBuilder.Entity("ShipItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipItem");
                });

            modelBuilder.Entity("Currencies", b =>
                {
                    b.HasOne("Player", null)
                        .WithOne("Currencies")
                        .HasForeignKey("Currencies", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Energy", b =>
                {
                    b.HasOne("Player", null)
                        .WithOne("Energy")
                        .HasForeignKey("Energy", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Experience", b =>
                {
                    b.HasOne("Player", null)
                        .WithOne("Experience")
                        .HasForeignKey("Experience", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.HasOne("Inventory", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryPlayerId");

                    b.OwnsOne("ItemGridData", "Size", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<List<bool>>("Values")
                                .IsRequired()
                                .HasColumnType("boolean[]");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("ItemId");

                            b1.ToTable("Item");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("ItemStatsData", "StatsData", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("StatsData");

                            b1.HasKey("ItemId");

                            b1.ToTable("Item");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Size")
                        .IsRequired();

                    b.Navigation("StatsData")
                        .IsRequired();
                });

            modelBuilder.Entity("Ship", b =>
                {
                    b.HasOne("ShipInventory", "ShipInventory")
                        .WithMany("Ships")
                        .HasForeignKey("ShipInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ShipGrid", "Grid", b1 =>
                        {
                            b1.Property<Guid>("ShipId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("Cells")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("ShipId");

                            b1.ToTable("Ships");

                            b1.WithOwner()
                                .HasForeignKey("ShipId");
                        });

                    b.Navigation("Grid")
                        .IsRequired();

                    b.Navigation("ShipInventory");
                });

            modelBuilder.Entity("ShipItem", b =>
                {
                    b.HasOne("Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ship", "Ship")
                        .WithMany("Items")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Navigation("Currencies");

                    b.Navigation("Energy");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Ship", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShipInventory", b =>
                {
                    b.Navigation("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
